// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/acknowledgment.proto

package dsd.pubsub.protos;

public final class Acknowledgment {
  private Acknowledgment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string senderType = 1;</code>
     * @return The senderType.
     */
    java.lang.String getSenderType();
    /**
     * <code>string senderType = 1;</code>
     * @return The bytes for senderType.
     */
    com.google.protobuf.ByteString
        getSenderTypeBytes();

    /**
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    int getNum();

    /**
     * <code>string leadBrokerLocation = 3;</code>
     * @return The leadBrokerLocation.
     */
    java.lang.String getLeadBrokerLocation();
    /**
     * <code>string leadBrokerLocation = 3;</code>
     * @return The bytes for leadBrokerLocation.
     */
    com.google.protobuf.ByteString
        getLeadBrokerLocationBytes();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code ack}
   */
  public static final class ack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ack)
      ackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ack.newBuilder() to construct.
    private ack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ack() {
      senderType_ = "";
      leadBrokerLocation_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ack();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderType_ = s;
              break;
            }
            case 16: {

              num_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              leadBrokerLocation_ = s;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsd.pubsub.protos.Acknowledgment.internal_static_ack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsd.pubsub.protos.Acknowledgment.internal_static_ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsd.pubsub.protos.Acknowledgment.ack.class, dsd.pubsub.protos.Acknowledgment.ack.Builder.class);
    }

    public static final int SENDERTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderType_;
    /**
     * <code>string senderType = 1;</code>
     * @return The senderType.
     */
    @java.lang.Override
    public java.lang.String getSenderType() {
      java.lang.Object ref = senderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderType_ = s;
        return s;
      }
    }
    /**
     * <code>string senderType = 1;</code>
     * @return The bytes for senderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderTypeBytes() {
      java.lang.Object ref = senderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>int32 num = 2;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }

    public static final int LEADBROKERLOCATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object leadBrokerLocation_;
    /**
     * <code>string leadBrokerLocation = 3;</code>
     * @return The leadBrokerLocation.
     */
    @java.lang.Override
    public java.lang.String getLeadBrokerLocation() {
      java.lang.Object ref = leadBrokerLocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leadBrokerLocation_ = s;
        return s;
      }
    }
    /**
     * <code>string leadBrokerLocation = 3;</code>
     * @return The bytes for leadBrokerLocation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeadBrokerLocationBytes() {
      java.lang.Object ref = leadBrokerLocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leadBrokerLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderType_);
      }
      if (num_ != 0) {
        output.writeInt32(2, num_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leadBrokerLocation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, leadBrokerLocation_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderType_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leadBrokerLocation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, leadBrokerLocation_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dsd.pubsub.protos.Acknowledgment.ack)) {
        return super.equals(obj);
      }
      dsd.pubsub.protos.Acknowledgment.ack other = (dsd.pubsub.protos.Acknowledgment.ack) obj;

      if (!getSenderType()
          .equals(other.getSenderType())) return false;
      if (getNum()
          != other.getNum()) return false;
      if (!getLeadBrokerLocation()
          .equals(other.getLeadBrokerLocation())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSenderType().hashCode();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + LEADBROKERLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLeadBrokerLocation().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Acknowledgment.ack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dsd.pubsub.protos.Acknowledgment.ack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ack)
        dsd.pubsub.protos.Acknowledgment.ackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsd.pubsub.protos.Acknowledgment.internal_static_ack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsd.pubsub.protos.Acknowledgment.internal_static_ack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsd.pubsub.protos.Acknowledgment.ack.class, dsd.pubsub.protos.Acknowledgment.ack.Builder.class);
      }

      // Construct using dsd.pubsub.protos.Acknowledgment.ack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderType_ = "";

        num_ = 0;

        leadBrokerLocation_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsd.pubsub.protos.Acknowledgment.internal_static_ack_descriptor;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Acknowledgment.ack getDefaultInstanceForType() {
        return dsd.pubsub.protos.Acknowledgment.ack.getDefaultInstance();
      }

      @java.lang.Override
      public dsd.pubsub.protos.Acknowledgment.ack build() {
        dsd.pubsub.protos.Acknowledgment.ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Acknowledgment.ack buildPartial() {
        dsd.pubsub.protos.Acknowledgment.ack result = new dsd.pubsub.protos.Acknowledgment.ack(this);
        result.senderType_ = senderType_;
        result.num_ = num_;
        result.leadBrokerLocation_ = leadBrokerLocation_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsd.pubsub.protos.Acknowledgment.ack) {
          return mergeFrom((dsd.pubsub.protos.Acknowledgment.ack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsd.pubsub.protos.Acknowledgment.ack other) {
        if (other == dsd.pubsub.protos.Acknowledgment.ack.getDefaultInstance()) return this;
        if (!other.getSenderType().isEmpty()) {
          senderType_ = other.senderType_;
          onChanged();
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (!other.getLeadBrokerLocation().isEmpty()) {
          leadBrokerLocation_ = other.leadBrokerLocation_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsd.pubsub.protos.Acknowledgment.ack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsd.pubsub.protos.Acknowledgment.ack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object senderType_ = "";
      /**
       * <code>string senderType = 1;</code>
       * @return The senderType.
       */
      public java.lang.String getSenderType() {
        java.lang.Object ref = senderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderType = 1;</code>
       * @return The bytes for senderType.
       */
      public com.google.protobuf.ByteString
          getSenderTypeBytes() {
        java.lang.Object ref = senderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderType = 1;</code>
       * @param value The senderType to set.
       * @return This builder for chaining.
       */
      public Builder setSenderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderType() {
        
        senderType_ = getDefaultInstance().getSenderType();
        onChanged();
        return this;
      }
      /**
       * <code>string senderType = 1;</code>
       * @param value The bytes for senderType to set.
       * @return This builder for chaining.
       */
      public Builder setSenderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderType_ = value;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>int32 num = 2;</code>
       * @return The num.
       */
      @java.lang.Override
      public int getNum() {
        return num_;
      }
      /**
       * <code>int32 num = 2;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leadBrokerLocation_ = "";
      /**
       * <code>string leadBrokerLocation = 3;</code>
       * @return The leadBrokerLocation.
       */
      public java.lang.String getLeadBrokerLocation() {
        java.lang.Object ref = leadBrokerLocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leadBrokerLocation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string leadBrokerLocation = 3;</code>
       * @return The bytes for leadBrokerLocation.
       */
      public com.google.protobuf.ByteString
          getLeadBrokerLocationBytes() {
        java.lang.Object ref = leadBrokerLocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leadBrokerLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string leadBrokerLocation = 3;</code>
       * @param value The leadBrokerLocation to set.
       * @return This builder for chaining.
       */
      public Builder setLeadBrokerLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        leadBrokerLocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string leadBrokerLocation = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeadBrokerLocation() {
        
        leadBrokerLocation_ = getDefaultInstance().getLeadBrokerLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string leadBrokerLocation = 3;</code>
       * @param value The bytes for leadBrokerLocation to set.
       * @return This builder for chaining.
       */
      public Builder setLeadBrokerLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        leadBrokerLocation_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ack)
    }

    // @@protoc_insertion_point(class_scope:ack)
    private static final dsd.pubsub.protos.Acknowledgment.ack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dsd.pubsub.protos.Acknowledgment.ack();
    }

    public static dsd.pubsub.protos.Acknowledgment.ack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ack>
        PARSER = new com.google.protobuf.AbstractParser<ack>() {
      @java.lang.Override
      public ack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dsd.pubsub.protos.Acknowledgment.ack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protos/acknowledgment.proto\"P\n\003ack\022\022\n\n" +
      "senderType\030\001 \001(\t\022\013\n\003num\030\002 \001(\005\022\032\n\022leadBro" +
      "kerLocation\030\003 \001(\t\022\014\n\004data\030\004 \001(\014B#\n\021dsd.p" +
      "ubsub.protosB\016Acknowledgmentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ack_descriptor,
        new java.lang.String[] { "SenderType", "Num", "LeadBrokerLocation", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
