// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/brokerToLoadBalancer.proto

package dsd.pubsub.protos;

public final class BrokerToLoadBalancer {
  private BrokerToLoadBalancer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface lbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 senderID = 2;</code>
     * @return The senderID.
     */
    int getSenderID();

    /**
     * <code>int32 brokerID = 3;</code>
     * @return The brokerID.
     */
    int getBrokerID();

    /**
     * <pre>
     *memberinfo
     * </pre>
     *
     * <code>string hostName = 4;</code>
     * @return The hostName.
     */
    java.lang.String getHostName();
    /**
     * <pre>
     *memberinfo
     * </pre>
     *
     * <code>string hostName = 4;</code>
     * @return The bytes for hostName.
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>string token = 6;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 6;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>bool isLeader = 7;</code>
     * @return The isLeader.
     */
    boolean getIsLeader();

    /**
     * <code>bool isAlive = 8;</code>
     * @return The isAlive.
     */
    boolean getIsAlive();
  }
  /**
   * <pre>
   *  message MemberInfo{
   *    string hostName = 1;
   *    int32 port = 2;
   *    string token = 3;
   *    bool isLeader = 4;
   *    bool isAlive = 5;
   *  }
   *  message MembershipTable{
   *    map&lt;int32, MemberInfo&gt; table = 6;
   *  }
   * </pre>
   *
   * Protobuf type {@code lb}
   */
  public static final class lb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lb)
      lbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use lb.newBuilder() to construct.
    private lb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private lb() {
      type_ = "";
      hostName_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new lb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private lb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              senderID_ = input.readInt32();
              break;
            }
            case 24: {

              brokerID_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 40: {

              port_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 56: {

              isLeader_ = input.readBool();
              break;
            }
            case 64: {

              isAlive_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsd.pubsub.protos.BrokerToLoadBalancer.internal_static_lb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsd.pubsub.protos.BrokerToLoadBalancer.internal_static_lb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsd.pubsub.protos.BrokerToLoadBalancer.lb.class, dsd.pubsub.protos.BrokerToLoadBalancer.lb.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 2;
    private int senderID_;
    /**
     * <code>int32 senderID = 2;</code>
     * @return The senderID.
     */
    @java.lang.Override
    public int getSenderID() {
      return senderID_;
    }

    public static final int BROKERID_FIELD_NUMBER = 3;
    private int brokerID_;
    /**
     * <code>int32 brokerID = 3;</code>
     * @return The brokerID.
     */
    @java.lang.Override
    public int getBrokerID() {
      return brokerID_;
    }

    public static final int HOSTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object hostName_;
    /**
     * <pre>
     *memberinfo
     * </pre>
     *
     * <code>string hostName = 4;</code>
     * @return The hostName.
     */
    @java.lang.Override
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *memberinfo
     * </pre>
     *
     * <code>string hostName = 4;</code>
     * @return The bytes for hostName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int TOKEN_FIELD_NUMBER = 6;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 6;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 6;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISLEADER_FIELD_NUMBER = 7;
    private boolean isLeader_;
    /**
     * <code>bool isLeader = 7;</code>
     * @return The isLeader.
     */
    @java.lang.Override
    public boolean getIsLeader() {
      return isLeader_;
    }

    public static final int ISALIVE_FIELD_NUMBER = 8;
    private boolean isAlive_;
    /**
     * <code>bool isAlive = 8;</code>
     * @return The isAlive.
     */
    @java.lang.Override
    public boolean getIsAlive() {
      return isAlive_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (senderID_ != 0) {
        output.writeInt32(2, senderID_);
      }
      if (brokerID_ != 0) {
        output.writeInt32(3, brokerID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hostName_);
      }
      if (port_ != 0) {
        output.writeInt32(5, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, token_);
      }
      if (isLeader_ != false) {
        output.writeBool(7, isLeader_);
      }
      if (isAlive_ != false) {
        output.writeBool(8, isAlive_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (senderID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, senderID_);
      }
      if (brokerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, brokerID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hostName_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, token_);
      }
      if (isLeader_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isLeader_);
      }
      if (isAlive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isAlive_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dsd.pubsub.protos.BrokerToLoadBalancer.lb)) {
        return super.equals(obj);
      }
      dsd.pubsub.protos.BrokerToLoadBalancer.lb other = (dsd.pubsub.protos.BrokerToLoadBalancer.lb) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (getSenderID()
          != other.getSenderID()) return false;
      if (getBrokerID()
          != other.getBrokerID()) return false;
      if (!getHostName()
          .equals(other.getHostName())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getIsLeader()
          != other.getIsLeader()) return false;
      if (getIsAlive()
          != other.getIsAlive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID();
      hash = (37 * hash) + BROKERID_FIELD_NUMBER;
      hash = (53 * hash) + getBrokerID();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ISLEADER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLeader());
      hash = (37 * hash) + ISALIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAlive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dsd.pubsub.protos.BrokerToLoadBalancer.lb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *  message MemberInfo{
     *    string hostName = 1;
     *    int32 port = 2;
     *    string token = 3;
     *    bool isLeader = 4;
     *    bool isAlive = 5;
     *  }
     *  message MembershipTable{
     *    map&lt;int32, MemberInfo&gt; table = 6;
     *  }
     * </pre>
     *
     * Protobuf type {@code lb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lb)
        dsd.pubsub.protos.BrokerToLoadBalancer.lbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsd.pubsub.protos.BrokerToLoadBalancer.internal_static_lb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsd.pubsub.protos.BrokerToLoadBalancer.internal_static_lb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsd.pubsub.protos.BrokerToLoadBalancer.lb.class, dsd.pubsub.protos.BrokerToLoadBalancer.lb.Builder.class);
      }

      // Construct using dsd.pubsub.protos.BrokerToLoadBalancer.lb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        senderID_ = 0;

        brokerID_ = 0;

        hostName_ = "";

        port_ = 0;

        token_ = "";

        isLeader_ = false;

        isAlive_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsd.pubsub.protos.BrokerToLoadBalancer.internal_static_lb_descriptor;
      }

      @java.lang.Override
      public dsd.pubsub.protos.BrokerToLoadBalancer.lb getDefaultInstanceForType() {
        return dsd.pubsub.protos.BrokerToLoadBalancer.lb.getDefaultInstance();
      }

      @java.lang.Override
      public dsd.pubsub.protos.BrokerToLoadBalancer.lb build() {
        dsd.pubsub.protos.BrokerToLoadBalancer.lb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dsd.pubsub.protos.BrokerToLoadBalancer.lb buildPartial() {
        dsd.pubsub.protos.BrokerToLoadBalancer.lb result = new dsd.pubsub.protos.BrokerToLoadBalancer.lb(this);
        result.type_ = type_;
        result.senderID_ = senderID_;
        result.brokerID_ = brokerID_;
        result.hostName_ = hostName_;
        result.port_ = port_;
        result.token_ = token_;
        result.isLeader_ = isLeader_;
        result.isAlive_ = isAlive_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsd.pubsub.protos.BrokerToLoadBalancer.lb) {
          return mergeFrom((dsd.pubsub.protos.BrokerToLoadBalancer.lb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsd.pubsub.protos.BrokerToLoadBalancer.lb other) {
        if (other == dsd.pubsub.protos.BrokerToLoadBalancer.lb.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getSenderID() != 0) {
          setSenderID(other.getSenderID());
        }
        if (other.getBrokerID() != 0) {
          setBrokerID(other.getBrokerID());
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getIsLeader() != false) {
          setIsLeader(other.getIsLeader());
        }
        if (other.getIsAlive() != false) {
          setIsAlive(other.getIsAlive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsd.pubsub.protos.BrokerToLoadBalancer.lb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsd.pubsub.protos.BrokerToLoadBalancer.lb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int senderID_ ;
      /**
       * <code>int32 senderID = 2;</code>
       * @return The senderID.
       */
      @java.lang.Override
      public int getSenderID() {
        return senderID_;
      }
      /**
       * <code>int32 senderID = 2;</code>
       * @param value The senderID to set.
       * @return This builder for chaining.
       */
      public Builder setSenderID(int value) {
        
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senderID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderID() {
        
        senderID_ = 0;
        onChanged();
        return this;
      }

      private int brokerID_ ;
      /**
       * <code>int32 brokerID = 3;</code>
       * @return The brokerID.
       */
      @java.lang.Override
      public int getBrokerID() {
        return brokerID_;
      }
      /**
       * <code>int32 brokerID = 3;</code>
       * @param value The brokerID to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerID(int value) {
        
        brokerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 brokerID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerID() {
        
        brokerID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object hostName_ = "";
      /**
       * <pre>
       *memberinfo
       * </pre>
       *
       * <code>string hostName = 4;</code>
       * @return The hostName.
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *memberinfo
       * </pre>
       *
       * <code>string hostName = 4;</code>
       * @return The bytes for hostName.
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *memberinfo
       * </pre>
       *
       * <code>string hostName = 4;</code>
       * @param value The hostName to set.
       * @return This builder for chaining.
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *memberinfo
       * </pre>
       *
       * <code>string hostName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostName() {
        
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *memberinfo
       * </pre>
       *
       * <code>string hostName = 4;</code>
       * @param value The bytes for hostName to set.
       * @return This builder for chaining.
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostName_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 5;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 5;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 6;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 6;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 6;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 6;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private boolean isLeader_ ;
      /**
       * <code>bool isLeader = 7;</code>
       * @return The isLeader.
       */
      @java.lang.Override
      public boolean getIsLeader() {
        return isLeader_;
      }
      /**
       * <code>bool isLeader = 7;</code>
       * @param value The isLeader to set.
       * @return This builder for chaining.
       */
      public Builder setIsLeader(boolean value) {
        
        isLeader_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isLeader = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLeader() {
        
        isLeader_ = false;
        onChanged();
        return this;
      }

      private boolean isAlive_ ;
      /**
       * <code>bool isAlive = 8;</code>
       * @return The isAlive.
       */
      @java.lang.Override
      public boolean getIsAlive() {
        return isAlive_;
      }
      /**
       * <code>bool isAlive = 8;</code>
       * @param value The isAlive to set.
       * @return This builder for chaining.
       */
      public Builder setIsAlive(boolean value) {
        
        isAlive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAlive = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAlive() {
        
        isAlive_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lb)
    }

    // @@protoc_insertion_point(class_scope:lb)
    private static final dsd.pubsub.protos.BrokerToLoadBalancer.lb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dsd.pubsub.protos.BrokerToLoadBalancer.lb();
    }

    public static dsd.pubsub.protos.BrokerToLoadBalancer.lb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<lb>
        PARSER = new com.google.protobuf.AbstractParser<lb>() {
      @java.lang.Override
      public lb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new lb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<lb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<lb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dsd.pubsub.protos.BrokerToLoadBalancer.lb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protos/brokerToLoadBalancer.proto\"\210\001\n\002" +
      "lb\022\014\n\004type\030\001 \001(\t\022\020\n\010senderID\030\002 \001(\005\022\020\n\010br" +
      "okerID\030\003 \001(\005\022\020\n\010hostName\030\004 \001(\t\022\014\n\004port\030\005" +
      " \001(\005\022\r\n\005token\030\006 \001(\t\022\020\n\010isLeader\030\007 \001(\010\022\017\n" +
      "\007isAlive\030\010 \001(\010B)\n\021dsd.pubsub.protosB\024Bro" +
      "kerToLoadBalancerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lb_descriptor,
        new java.lang.String[] { "Type", "SenderID", "BrokerID", "HostName", "Port", "Token", "IsLeader", "IsAlive", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
