// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/response.proto

package dsd.pubsub.protos;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 senderID = 1;</code>
     * @return The senderID.
     */
    int getSenderID();

    /**
     * <code>int32 numOfRetires = 2;</code>
     * @return The numOfRetires.
     */
    int getNumOfRetires();
  }
  /**
   * Protobuf type {@code HeartBeat}
   */
  public static final class HeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeat)
      HeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              senderID_ = input.readInt32();
              break;
            }
            case 16: {

              numOfRetires_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsd.pubsub.protos.Response.internal_static_HeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsd.pubsub.protos.Response.internal_static_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsd.pubsub.protos.Response.HeartBeat.class, dsd.pubsub.protos.Response.HeartBeat.Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderID_;
    /**
     * <code>int32 senderID = 1;</code>
     * @return The senderID.
     */
    @java.lang.Override
    public int getSenderID() {
      return senderID_;
    }

    public static final int NUMOFRETIRES_FIELD_NUMBER = 2;
    private int numOfRetires_;
    /**
     * <code>int32 numOfRetires = 2;</code>
     * @return The numOfRetires.
     */
    @java.lang.Override
    public int getNumOfRetires() {
      return numOfRetires_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderID_ != 0) {
        output.writeInt32(1, senderID_);
      }
      if (numOfRetires_ != 0) {
        output.writeInt32(2, numOfRetires_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderID_);
      }
      if (numOfRetires_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numOfRetires_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dsd.pubsub.protos.Response.HeartBeat)) {
        return super.equals(obj);
      }
      dsd.pubsub.protos.Response.HeartBeat other = (dsd.pubsub.protos.Response.HeartBeat) obj;

      if (getSenderID()
          != other.getSenderID()) return false;
      if (getNumOfRetires()
          != other.getNumOfRetires()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID();
      hash = (37 * hash) + NUMOFRETIRES_FIELD_NUMBER;
      hash = (53 * hash) + getNumOfRetires();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dsd.pubsub.protos.Response.HeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat)
        dsd.pubsub.protos.Response.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsd.pubsub.protos.Response.internal_static_HeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsd.pubsub.protos.Response.internal_static_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsd.pubsub.protos.Response.HeartBeat.class, dsd.pubsub.protos.Response.HeartBeat.Builder.class);
      }

      // Construct using dsd.pubsub.protos.Response.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderID_ = 0;

        numOfRetires_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsd.pubsub.protos.Response.internal_static_HeartBeat_descriptor;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.HeartBeat getDefaultInstanceForType() {
        return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.HeartBeat build() {
        dsd.pubsub.protos.Response.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.HeartBeat buildPartial() {
        dsd.pubsub.protos.Response.HeartBeat result = new dsd.pubsub.protos.Response.HeartBeat(this);
        result.senderID_ = senderID_;
        result.numOfRetires_ = numOfRetires_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsd.pubsub.protos.Response.HeartBeat) {
          return mergeFrom((dsd.pubsub.protos.Response.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsd.pubsub.protos.Response.HeartBeat other) {
        if (other == dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance()) return this;
        if (other.getSenderID() != 0) {
          setSenderID(other.getSenderID());
        }
        if (other.getNumOfRetires() != 0) {
          setNumOfRetires(other.getNumOfRetires());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsd.pubsub.protos.Response.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsd.pubsub.protos.Response.HeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int senderID_ ;
      /**
       * <code>int32 senderID = 1;</code>
       * @return The senderID.
       */
      @java.lang.Override
      public int getSenderID() {
        return senderID_;
      }
      /**
       * <code>int32 senderID = 1;</code>
       * @param value The senderID to set.
       * @return This builder for chaining.
       */
      public Builder setSenderID(int value) {
        
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senderID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderID() {
        
        senderID_ = 0;
        onChanged();
        return this;
      }

      private int numOfRetires_ ;
      /**
       * <code>int32 numOfRetires = 2;</code>
       * @return The numOfRetires.
       */
      @java.lang.Override
      public int getNumOfRetires() {
        return numOfRetires_;
      }
      /**
       * <code>int32 numOfRetires = 2;</code>
       * @param value The numOfRetires to set.
       * @return This builder for chaining.
       */
      public Builder setNumOfRetires(int value) {
        
        numOfRetires_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numOfRetires = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumOfRetires() {
        
        numOfRetires_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeat)
    }

    // @@protoc_insertion_point(class_scope:HeartBeat)
    private static final dsd.pubsub.protos.Response.HeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dsd.pubsub.protos.Response.HeartBeat();
    }

    public static dsd.pubsub.protos.Response.HeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
      @java.lang.Override
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dsd.pubsub.protos.Response.HeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ElectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Election)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 senderID = 1;</code>
     * @return The senderID.
     */
    int getSenderID();

    /**
     * <code>int32 winnerID = 2;</code>
     * @return The winnerID.
     */
    int getWinnerID();
  }
  /**
   * Protobuf type {@code Election}
   */
  public static final class Election extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Election)
      ElectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Election.newBuilder() to construct.
    private Election(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Election() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Election();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Election(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              senderID_ = input.readInt32();
              break;
            }
            case 16: {

              winnerID_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsd.pubsub.protos.Response.internal_static_Election_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsd.pubsub.protos.Response.internal_static_Election_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsd.pubsub.protos.Response.Election.class, dsd.pubsub.protos.Response.Election.Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderID_;
    /**
     * <code>int32 senderID = 1;</code>
     * @return The senderID.
     */
    @java.lang.Override
    public int getSenderID() {
      return senderID_;
    }

    public static final int WINNERID_FIELD_NUMBER = 2;
    private int winnerID_;
    /**
     * <code>int32 winnerID = 2;</code>
     * @return The winnerID.
     */
    @java.lang.Override
    public int getWinnerID() {
      return winnerID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderID_ != 0) {
        output.writeInt32(1, senderID_);
      }
      if (winnerID_ != 0) {
        output.writeInt32(2, winnerID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderID_);
      }
      if (winnerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, winnerID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dsd.pubsub.protos.Response.Election)) {
        return super.equals(obj);
      }
      dsd.pubsub.protos.Response.Election other = (dsd.pubsub.protos.Response.Election) obj;

      if (getSenderID()
          != other.getSenderID()) return false;
      if (getWinnerID()
          != other.getWinnerID()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID();
      hash = (37 * hash) + WINNERID_FIELD_NUMBER;
      hash = (53 * hash) + getWinnerID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dsd.pubsub.protos.Response.Election parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.Election parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.Election parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.Election parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dsd.pubsub.protos.Response.Election prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Election}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Election)
        dsd.pubsub.protos.Response.ElectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsd.pubsub.protos.Response.internal_static_Election_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsd.pubsub.protos.Response.internal_static_Election_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsd.pubsub.protos.Response.Election.class, dsd.pubsub.protos.Response.Election.Builder.class);
      }

      // Construct using dsd.pubsub.protos.Response.Election.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderID_ = 0;

        winnerID_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsd.pubsub.protos.Response.internal_static_Election_descriptor;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.Election getDefaultInstanceForType() {
        return dsd.pubsub.protos.Response.Election.getDefaultInstance();
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.Election build() {
        dsd.pubsub.protos.Response.Election result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.Election buildPartial() {
        dsd.pubsub.protos.Response.Election result = new dsd.pubsub.protos.Response.Election(this);
        result.senderID_ = senderID_;
        result.winnerID_ = winnerID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsd.pubsub.protos.Response.Election) {
          return mergeFrom((dsd.pubsub.protos.Response.Election)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsd.pubsub.protos.Response.Election other) {
        if (other == dsd.pubsub.protos.Response.Election.getDefaultInstance()) return this;
        if (other.getSenderID() != 0) {
          setSenderID(other.getSenderID());
        }
        if (other.getWinnerID() != 0) {
          setWinnerID(other.getWinnerID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsd.pubsub.protos.Response.Election parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsd.pubsub.protos.Response.Election) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int senderID_ ;
      /**
       * <code>int32 senderID = 1;</code>
       * @return The senderID.
       */
      @java.lang.Override
      public int getSenderID() {
        return senderID_;
      }
      /**
       * <code>int32 senderID = 1;</code>
       * @param value The senderID to set.
       * @return This builder for chaining.
       */
      public Builder setSenderID(int value) {
        
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senderID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderID() {
        
        senderID_ = 0;
        onChanged();
        return this;
      }

      private int winnerID_ ;
      /**
       * <code>int32 winnerID = 2;</code>
       * @return The winnerID.
       */
      @java.lang.Override
      public int getWinnerID() {
        return winnerID_;
      }
      /**
       * <code>int32 winnerID = 2;</code>
       * @param value The winnerID to set.
       * @return This builder for chaining.
       */
      public Builder setWinnerID(int value) {
        
        winnerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 winnerID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWinnerID() {
        
        winnerID_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Election)
    }

    // @@protoc_insertion_point(class_scope:Election)
    private static final dsd.pubsub.protos.Response.Election DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dsd.pubsub.protos.Response.Election();
    }

    public static dsd.pubsub.protos.Response.Election getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Election>
        PARSER = new com.google.protobuf.AbstractParser<Election>() {
      @java.lang.Override
      public Election parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Election(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Election> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Election> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dsd.pubsub.protos.Response.Election getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OneResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OneResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     * @return Whether the heartBeat field is set.
     */
    boolean hasHeartBeat();
    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     * @return The heartBeat.
     */
    dsd.pubsub.protos.Response.HeartBeat getHeartBeat();
    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     */
    dsd.pubsub.protos.Response.HeartBeatOrBuilder getHeartBeatOrBuilder();

    /**
     * <code>.Election election = 2;</code>
     * @return Whether the election field is set.
     */
    boolean hasElection();
    /**
     * <code>.Election election = 2;</code>
     * @return The election.
     */
    dsd.pubsub.protos.Response.Election getElection();
    /**
     * <code>.Election election = 2;</code>
     */
    dsd.pubsub.protos.Response.ElectionOrBuilder getElectionOrBuilder();

    public dsd.pubsub.protos.Response.OneResponse.RespCase getRespCase();
  }
  /**
   * Protobuf type {@code OneResponse}
   */
  public static final class OneResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OneResponse)
      OneResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneResponse.newBuilder() to construct.
    private OneResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OneResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dsd.pubsub.protos.Response.HeartBeat.Builder subBuilder = null;
              if (respCase_ == 1) {
                subBuilder = ((dsd.pubsub.protos.Response.HeartBeat) resp_).toBuilder();
              }
              resp_ =
                  input.readMessage(dsd.pubsub.protos.Response.HeartBeat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((dsd.pubsub.protos.Response.HeartBeat) resp_);
                resp_ = subBuilder.buildPartial();
              }
              respCase_ = 1;
              break;
            }
            case 18: {
              dsd.pubsub.protos.Response.Election.Builder subBuilder = null;
              if (respCase_ == 2) {
                subBuilder = ((dsd.pubsub.protos.Response.Election) resp_).toBuilder();
              }
              resp_ =
                  input.readMessage(dsd.pubsub.protos.Response.Election.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((dsd.pubsub.protos.Response.Election) resp_);
                resp_ = subBuilder.buildPartial();
              }
              respCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsd.pubsub.protos.Response.internal_static_OneResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsd.pubsub.protos.Response.internal_static_OneResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsd.pubsub.protos.Response.OneResponse.class, dsd.pubsub.protos.Response.OneResponse.Builder.class);
    }

    private int respCase_ = 0;
    private java.lang.Object resp_;
    public enum RespCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      HEARTBEAT(1),
      ELECTION(2),
      RESP_NOT_SET(0);
      private final int value;
      private RespCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RespCase valueOf(int value) {
        return forNumber(value);
      }

      public static RespCase forNumber(int value) {
        switch (value) {
          case 1: return HEARTBEAT;
          case 2: return ELECTION;
          case 0: return RESP_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public RespCase
    getRespCase() {
      return RespCase.forNumber(
          respCase_);
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 1;
    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     * @return Whether the heartBeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartBeat() {
      return respCase_ == 1;
    }
    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     * @return The heartBeat.
     */
    @java.lang.Override
    public dsd.pubsub.protos.Response.HeartBeat getHeartBeat() {
      if (respCase_ == 1) {
         return (dsd.pubsub.protos.Response.HeartBeat) resp_;
      }
      return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
    }
    /**
     * <code>.HeartBeat heartBeat = 1;</code>
     */
    @java.lang.Override
    public dsd.pubsub.protos.Response.HeartBeatOrBuilder getHeartBeatOrBuilder() {
      if (respCase_ == 1) {
         return (dsd.pubsub.protos.Response.HeartBeat) resp_;
      }
      return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
    }

    public static final int ELECTION_FIELD_NUMBER = 2;
    /**
     * <code>.Election election = 2;</code>
     * @return Whether the election field is set.
     */
    @java.lang.Override
    public boolean hasElection() {
      return respCase_ == 2;
    }
    /**
     * <code>.Election election = 2;</code>
     * @return The election.
     */
    @java.lang.Override
    public dsd.pubsub.protos.Response.Election getElection() {
      if (respCase_ == 2) {
         return (dsd.pubsub.protos.Response.Election) resp_;
      }
      return dsd.pubsub.protos.Response.Election.getDefaultInstance();
    }
    /**
     * <code>.Election election = 2;</code>
     */
    @java.lang.Override
    public dsd.pubsub.protos.Response.ElectionOrBuilder getElectionOrBuilder() {
      if (respCase_ == 2) {
         return (dsd.pubsub.protos.Response.Election) resp_;
      }
      return dsd.pubsub.protos.Response.Election.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (respCase_ == 1) {
        output.writeMessage(1, (dsd.pubsub.protos.Response.HeartBeat) resp_);
      }
      if (respCase_ == 2) {
        output.writeMessage(2, (dsd.pubsub.protos.Response.Election) resp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (respCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dsd.pubsub.protos.Response.HeartBeat) resp_);
      }
      if (respCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dsd.pubsub.protos.Response.Election) resp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dsd.pubsub.protos.Response.OneResponse)) {
        return super.equals(obj);
      }
      dsd.pubsub.protos.Response.OneResponse other = (dsd.pubsub.protos.Response.OneResponse) obj;

      if (!getRespCase().equals(other.getRespCase())) return false;
      switch (respCase_) {
        case 1:
          if (!getHeartBeat()
              .equals(other.getHeartBeat())) return false;
          break;
        case 2:
          if (!getElection()
              .equals(other.getElection())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (respCase_) {
        case 1:
          hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getHeartBeat().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ELECTION_FIELD_NUMBER;
          hash = (53 * hash) + getElection().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dsd.pubsub.protos.Response.OneResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dsd.pubsub.protos.Response.OneResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OneResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OneResponse)
        dsd.pubsub.protos.Response.OneResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsd.pubsub.protos.Response.internal_static_OneResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsd.pubsub.protos.Response.internal_static_OneResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsd.pubsub.protos.Response.OneResponse.class, dsd.pubsub.protos.Response.OneResponse.Builder.class);
      }

      // Construct using dsd.pubsub.protos.Response.OneResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        respCase_ = 0;
        resp_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsd.pubsub.protos.Response.internal_static_OneResponse_descriptor;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.OneResponse getDefaultInstanceForType() {
        return dsd.pubsub.protos.Response.OneResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.OneResponse build() {
        dsd.pubsub.protos.Response.OneResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dsd.pubsub.protos.Response.OneResponse buildPartial() {
        dsd.pubsub.protos.Response.OneResponse result = new dsd.pubsub.protos.Response.OneResponse(this);
        if (respCase_ == 1) {
          if (heartBeatBuilder_ == null) {
            result.resp_ = resp_;
          } else {
            result.resp_ = heartBeatBuilder_.build();
          }
        }
        if (respCase_ == 2) {
          if (electionBuilder_ == null) {
            result.resp_ = resp_;
          } else {
            result.resp_ = electionBuilder_.build();
          }
        }
        result.respCase_ = respCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsd.pubsub.protos.Response.OneResponse) {
          return mergeFrom((dsd.pubsub.protos.Response.OneResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsd.pubsub.protos.Response.OneResponse other) {
        if (other == dsd.pubsub.protos.Response.OneResponse.getDefaultInstance()) return this;
        switch (other.getRespCase()) {
          case HEARTBEAT: {
            mergeHeartBeat(other.getHeartBeat());
            break;
          }
          case ELECTION: {
            mergeElection(other.getElection());
            break;
          }
          case RESP_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsd.pubsub.protos.Response.OneResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsd.pubsub.protos.Response.OneResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int respCase_ = 0;
      private java.lang.Object resp_;
      public RespCase
          getRespCase() {
        return RespCase.forNumber(
            respCase_);
      }

      public Builder clearResp() {
        respCase_ = 0;
        resp_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          dsd.pubsub.protos.Response.HeartBeat, dsd.pubsub.protos.Response.HeartBeat.Builder, dsd.pubsub.protos.Response.HeartBeatOrBuilder> heartBeatBuilder_;
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       * @return Whether the heartBeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartBeat() {
        return respCase_ == 1;
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       * @return The heartBeat.
       */
      @java.lang.Override
      public dsd.pubsub.protos.Response.HeartBeat getHeartBeat() {
        if (heartBeatBuilder_ == null) {
          if (respCase_ == 1) {
            return (dsd.pubsub.protos.Response.HeartBeat) resp_;
          }
          return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
        } else {
          if (respCase_ == 1) {
            return heartBeatBuilder_.getMessage();
          }
          return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      public Builder setHeartBeat(dsd.pubsub.protos.Response.HeartBeat value) {
        if (heartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resp_ = value;
          onChanged();
        } else {
          heartBeatBuilder_.setMessage(value);
        }
        respCase_ = 1;
        return this;
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      public Builder setHeartBeat(
          dsd.pubsub.protos.Response.HeartBeat.Builder builderForValue) {
        if (heartBeatBuilder_ == null) {
          resp_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatBuilder_.setMessage(builderForValue.build());
        }
        respCase_ = 1;
        return this;
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      public Builder mergeHeartBeat(dsd.pubsub.protos.Response.HeartBeat value) {
        if (heartBeatBuilder_ == null) {
          if (respCase_ == 1 &&
              resp_ != dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance()) {
            resp_ = dsd.pubsub.protos.Response.HeartBeat.newBuilder((dsd.pubsub.protos.Response.HeartBeat) resp_)
                .mergeFrom(value).buildPartial();
          } else {
            resp_ = value;
          }
          onChanged();
        } else {
          if (respCase_ == 1) {
            heartBeatBuilder_.mergeFrom(value);
          }
          heartBeatBuilder_.setMessage(value);
        }
        respCase_ = 1;
        return this;
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      public Builder clearHeartBeat() {
        if (heartBeatBuilder_ == null) {
          if (respCase_ == 1) {
            respCase_ = 0;
            resp_ = null;
            onChanged();
          }
        } else {
          if (respCase_ == 1) {
            respCase_ = 0;
            resp_ = null;
          }
          heartBeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      public dsd.pubsub.protos.Response.HeartBeat.Builder getHeartBeatBuilder() {
        return getHeartBeatFieldBuilder().getBuilder();
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      @java.lang.Override
      public dsd.pubsub.protos.Response.HeartBeatOrBuilder getHeartBeatOrBuilder() {
        if ((respCase_ == 1) && (heartBeatBuilder_ != null)) {
          return heartBeatBuilder_.getMessageOrBuilder();
        } else {
          if (respCase_ == 1) {
            return (dsd.pubsub.protos.Response.HeartBeat) resp_;
          }
          return dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>.HeartBeat heartBeat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dsd.pubsub.protos.Response.HeartBeat, dsd.pubsub.protos.Response.HeartBeat.Builder, dsd.pubsub.protos.Response.HeartBeatOrBuilder> 
          getHeartBeatFieldBuilder() {
        if (heartBeatBuilder_ == null) {
          if (!(respCase_ == 1)) {
            resp_ = dsd.pubsub.protos.Response.HeartBeat.getDefaultInstance();
          }
          heartBeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dsd.pubsub.protos.Response.HeartBeat, dsd.pubsub.protos.Response.HeartBeat.Builder, dsd.pubsub.protos.Response.HeartBeatOrBuilder>(
                  (dsd.pubsub.protos.Response.HeartBeat) resp_,
                  getParentForChildren(),
                  isClean());
          resp_ = null;
        }
        respCase_ = 1;
        onChanged();;
        return heartBeatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          dsd.pubsub.protos.Response.Election, dsd.pubsub.protos.Response.Election.Builder, dsd.pubsub.protos.Response.ElectionOrBuilder> electionBuilder_;
      /**
       * <code>.Election election = 2;</code>
       * @return Whether the election field is set.
       */
      @java.lang.Override
      public boolean hasElection() {
        return respCase_ == 2;
      }
      /**
       * <code>.Election election = 2;</code>
       * @return The election.
       */
      @java.lang.Override
      public dsd.pubsub.protos.Response.Election getElection() {
        if (electionBuilder_ == null) {
          if (respCase_ == 2) {
            return (dsd.pubsub.protos.Response.Election) resp_;
          }
          return dsd.pubsub.protos.Response.Election.getDefaultInstance();
        } else {
          if (respCase_ == 2) {
            return electionBuilder_.getMessage();
          }
          return dsd.pubsub.protos.Response.Election.getDefaultInstance();
        }
      }
      /**
       * <code>.Election election = 2;</code>
       */
      public Builder setElection(dsd.pubsub.protos.Response.Election value) {
        if (electionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resp_ = value;
          onChanged();
        } else {
          electionBuilder_.setMessage(value);
        }
        respCase_ = 2;
        return this;
      }
      /**
       * <code>.Election election = 2;</code>
       */
      public Builder setElection(
          dsd.pubsub.protos.Response.Election.Builder builderForValue) {
        if (electionBuilder_ == null) {
          resp_ = builderForValue.build();
          onChanged();
        } else {
          electionBuilder_.setMessage(builderForValue.build());
        }
        respCase_ = 2;
        return this;
      }
      /**
       * <code>.Election election = 2;</code>
       */
      public Builder mergeElection(dsd.pubsub.protos.Response.Election value) {
        if (electionBuilder_ == null) {
          if (respCase_ == 2 &&
              resp_ != dsd.pubsub.protos.Response.Election.getDefaultInstance()) {
            resp_ = dsd.pubsub.protos.Response.Election.newBuilder((dsd.pubsub.protos.Response.Election) resp_)
                .mergeFrom(value).buildPartial();
          } else {
            resp_ = value;
          }
          onChanged();
        } else {
          if (respCase_ == 2) {
            electionBuilder_.mergeFrom(value);
          }
          electionBuilder_.setMessage(value);
        }
        respCase_ = 2;
        return this;
      }
      /**
       * <code>.Election election = 2;</code>
       */
      public Builder clearElection() {
        if (electionBuilder_ == null) {
          if (respCase_ == 2) {
            respCase_ = 0;
            resp_ = null;
            onChanged();
          }
        } else {
          if (respCase_ == 2) {
            respCase_ = 0;
            resp_ = null;
          }
          electionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Election election = 2;</code>
       */
      public dsd.pubsub.protos.Response.Election.Builder getElectionBuilder() {
        return getElectionFieldBuilder().getBuilder();
      }
      /**
       * <code>.Election election = 2;</code>
       */
      @java.lang.Override
      public dsd.pubsub.protos.Response.ElectionOrBuilder getElectionOrBuilder() {
        if ((respCase_ == 2) && (electionBuilder_ != null)) {
          return electionBuilder_.getMessageOrBuilder();
        } else {
          if (respCase_ == 2) {
            return (dsd.pubsub.protos.Response.Election) resp_;
          }
          return dsd.pubsub.protos.Response.Election.getDefaultInstance();
        }
      }
      /**
       * <code>.Election election = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dsd.pubsub.protos.Response.Election, dsd.pubsub.protos.Response.Election.Builder, dsd.pubsub.protos.Response.ElectionOrBuilder> 
          getElectionFieldBuilder() {
        if (electionBuilder_ == null) {
          if (!(respCase_ == 2)) {
            resp_ = dsd.pubsub.protos.Response.Election.getDefaultInstance();
          }
          electionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dsd.pubsub.protos.Response.Election, dsd.pubsub.protos.Response.Election.Builder, dsd.pubsub.protos.Response.ElectionOrBuilder>(
                  (dsd.pubsub.protos.Response.Election) resp_,
                  getParentForChildren(),
                  isClean());
          resp_ = null;
        }
        respCase_ = 2;
        onChanged();;
        return electionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OneResponse)
    }

    // @@protoc_insertion_point(class_scope:OneResponse)
    private static final dsd.pubsub.protos.Response.OneResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dsd.pubsub.protos.Response.OneResponse();
    }

    public static dsd.pubsub.protos.Response.OneResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OneResponse>
        PARSER = new com.google.protobuf.AbstractParser<OneResponse>() {
      @java.lang.Override
      public OneResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dsd.pubsub.protos.Response.OneResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Election_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Election_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OneResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protos/response.proto\"3\n\tHeartBeat\022\020\n\010" +
      "senderID\030\001 \001(\005\022\024\n\014numOfRetires\030\002 \001(\005\".\n\010" +
      "Election\022\020\n\010senderID\030\001 \001(\005\022\020\n\010winnerID\030\002" +
      " \001(\005\"U\n\013OneResponse\022\037\n\theartBeat\030\001 \001(\0132\n" +
      ".HeartBeatH\000\022\035\n\010election\030\002 \001(\0132\t.Electio" +
      "nH\000B\006\n\004respB\035\n\021dsd.pubsub.protosB\010Respon" +
      "seb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_descriptor,
        new java.lang.String[] { "SenderID", "NumOfRetires", });
    internal_static_Election_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Election_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Election_descriptor,
        new java.lang.String[] { "SenderID", "WinnerID", });
    internal_static_OneResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OneResponse_descriptor,
        new java.lang.String[] { "HeartBeat", "Election", "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
